name: ethio_tutor
description: A mobile app for learning Amharic and Afaan Oromo with AI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  record: ^4.4.4
  just_audio: ^0.9.36
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.0
  confetti: ^0.7.0
  shimmer: ^3.0.0
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  animations: ^2.0.11



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/achievements/
    - assets/vocabulary/
    - assets/scenarios/
